### PR TITLE
MAINT: Attempt to get pip to work correctly

### PR DESCRIPTION
**Pull request by bashtage**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bashtage** [comment]
@conda-forge-admin, please rerender

**Comment by bashtage** [comment]
For some reason, pip isn't getting the right version.  I am guessing this has to do with `setupmeta`.  When `pip check` is run I am getting versions like `formulaic 0.0.0+post18` even though the package is 0.3.2.

**Comment by bashtage** [comment]
`formulaic 0.0.0.post18+dirty has requirement interface-meta>=1.2, but you have interface-meta 0.0.0.post26+dirty`

**Comment by matthewwardrop** [comment]
Oh.... interesting. Thanks for letting me know. I'll make sure this gets fixed.

**Comment by matthewwardrop** [comment]
I've fixed this in #6, for formulaic >=0.3.3 (which has moved to poetry rather than setupmeta for dynamic versions).

**Comment by bashtage** [comment]
Thanks.  I verified it works correctly now.

**Pull request closed without merging**
